* 介绍

对已有的股票历史数据进行分析。现在提供了计算动量的功能。其需要的输入有
个股的历史行情数据和需要分析的股票代码集合。

* 历史数据

历史数据的位置通过getHistFile来获取，
因此需要参考或者修改这个函数来指向你的历史数据。所有的历史数据都位于
同一个目录，每只股票的历史数据放在一个单独的文件。

** 文件的命名方式

文件的命名方式是“[SH|SZ]<股票代码>.txt”。
比如万化化学的代码为600309 ，那么它对应的历史数据文件名为“SH600309.txt”
，利亚德德代码为300296 ，其对应的历史数据文件名为“SZ300296.txt”。

** 历史数据文件格式

每只股票的历史数据文件格式为txt文件。每行的内容为：
#+BEGIN_EXAMPLE
日期 开盘价 最高价 最低价 收盘价 成交量 成交金额
#+END_EXAMPLE

数据之间用空格分割。其中日期的格式为YYYY-MM-DD，以下为一个实例：

#+BEGIN_EXAMPLE
2016-10-24 21.43 21.66 21.20 21.40 8275344 177061472.00
2016-10-25 21.41 21.47 21.10 21.24 6333957 134417664.00
2016-10-26 21.23 21.24 20.80 21.15 9365944 196514176.00
2016-10-27 21.22 21.63 20.90 21.37 8906300 189783424.00
2016-10-28 21.43 21.47 21.25 21.39 5975900 127672808.00
#+END_EXAMPLE

如果日期数据是其他的格式，可以通过修改stockUtils.R文件中loadhist函数
调用read.zoo函数的参数。

** 输入数据的预处理

*** 去除多余的行

有时历史数据文件中会有其他的一些行，比如表头什么的。可以通过一些其他的
方式来去除这些无用行，但是这里有一个简单的命令可以做这件事：

#+BEGIN_SRC bash
sed -n -i -e "/^2/p"  SH600309.txt
#+END_SRC

这样可以把文件中所有不是以2开头的行删除。将后面的SH600309换成 =*= 就可以
修改目录下所有的文件，是比较方便的。之所以要保留以2开头的行，因为这里假设
所有的数据都是2000年以来的数据。

* 需要分析的代码集合

  需要分析的代码集合在dailyrunNew.R中的dongLiangSelect函数中指定。缺省使用的代码集
是创业300指数的成份股。放在./babkuai2/chuangye300.txt文件中。这个文件的格式是每行
一个代码，该文件的前几行如下所示：

#+BEGIN_EXAMPLE
300001
300002
300003
300004
300005
#+END_EXAMPLE

* 代码运行

   在确认getHistFile函数指向正确的历史数据以后并确认历史数据格式和上面描述的匹配以后。
更新当前的创业板300成份股到bankuai2/chuangye300.txt文件中。运行

#+BEGIN_SRC bash
Rscript  ./dailyrunNew.R
#+END_SRC

然后会在当前目录下生成一个chuangyeDongLiangTop.txt文件。其中包含了过去23个月中，动量
排名最靠前的10只股票。这个文件中只列出了代码。并没有包含其他的信息。


